# Generated by Django 6.0.3 on 2026-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
